//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naruto_UltimateNinjaWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTable
    {
        public string Name { get; set; }
        public Nullable<int> Chakra { get; set; }
        public Nullable<int> Ninjutsu { get; set; }
        public Nullable<int> body { get; set; }
        public Nullable<int> Hallucination { get; set; }
        public Nullable<int> Feel { get; set; }
        public Nullable<int> total { get; set; }
        public string group { get; set; }
        public Nullable<bool> have { get; set; }
        public Nullable<int> ShardCount { get; set; }
        public Nullable<int> CommonToken { get; set; }
    }
}
